version: 2
jobs:
  build:

    working_directory: ~/library-grad-project-java

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
    - checkout

    - restore_cache:
        key: library-grad-project-java-{{ checksum "pom.xml" }}

    - save_cache:
        paths:
        - ~/.m2
        key: library-grad-project-java-{{ checksum "pom.xml" }}

    - run:
        name: Package
        command: mvn package

    - run:
        name: Run server tests
        command: mvn surefire:test