version: 2
jobs:
  test_maven:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/maven-workspace

    steps:
      - checkout

      - attach_workspace:
          at: ~/maven-workspace

      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Setup Maven Dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Run Server Tests
          command: mvn package

      - persist_to_workspace:
          root: .
          paths: target/library-grad-project-1.0-SNAPSHOT.jar

  test_node:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          key: node-dependencies-{{ checksum "src/main/client/package.json" }}

      - run:
          name: Setup Node Dependencies
          command: cd src/main/client && npm install

      - save_cache:
          paths:
            - ./node_modules
          key: node-dependencies-{{ checksum "src/main/client/package.json" }}

      - run:
          name: Run Client Tests
          command: cd src/main/client && set CI=true && npm run test

  e2e_test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/maven-workspace

    steps:
      - checkout

      - attach_workspace:
          at: ~/maven-workspace

      # Run the jar - parallel
      - run:
          name: Run JAR file
          command: MAVEN_TEST=true java -jar target/library-grad-project-1.0-SNAPSHOT.jar

      # Run e2e tests - parallel

workflows:
  version: 2
  test_all:
    jobs:
      - test_maven
      - test_node
      - e2e_test:
          requires:
            - test_maven
